### ISSUE TITLE
Missing 'as React.ReactElement' on https://resend.com/docs/send-with-nextjs

### ISSUE THREAD

**Issue by zeekrey** [resend/resend-nextjs-app-router-example#19]
Hello! 👋🏻

I'm really enjoying your product! I wanted to bring to your attention a small observation regarding the example on https://resend.com/docs/send-with-nextjs. It seems that the type assertion `as React.ReactElement` is missing in line 14. I just wanted to let you know that the example repository is accurate, but the snippet in the quick start guide has a TypeScript issue.

Keep up the great work!

**Comment by saltcod** [comment]
+1 just ran into same
